# This is a basic workflow to help you get started with Actions

name: Build to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_to_pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
     
      - run: flutter pub get
      - run: flutter build web --release --web-renderer html
      
      - name: Pushes build to page
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.WORKFLOW }}
        with:
          source_file: 'build/web'
          destination_repo: 'eleven3000/eleven3000.github.io'
          user_email: 'eleven300011@gmail.com'
          user_name: 'eleven3000'
